public class StringExample 
{

    public static void main(String[] args)
	{
        String str1 = "Hello";
        String str2 = "World";
        String str3 = "Java";
        String str4 = "Programming";
        String str5 = "Language";
        String str6 = "Example";
        String str7 = "Strings";
        String str8 = "Concatenation";
        String str9 = "Sequence";
        String str10 = "Initialization";
        String str11 = "Learning";
        String str12 = "Code";
        String str13 = "Compile";
        String str14 = "Run";
        String str15 = "Execute";
        String str16 = "Variables";
        String str17 = "Data";
        String str18 = "Types";
        String str19 = "Classes";
        String str20 = "Methods";
        String str21 = "Objects";
        String str22 = "Functions";
        String str23 = "Logic";
        String str24 = "Operators";
        String str25 = "Loops";
        String str26 = "Conditionals";
        String str27 = "Arrays";
        String str28 = "Lists";
        String str29 = "Sets";
        String str30 = "Maps";
        String str31 = "Collections";
        String str32 = "Frameworks";
        String str33 = "Libraries";
        String str34 = "APIs";
        String str35 = "Interfaces";
        String str36 = "Abstract";
        String str37 = "Inheritance";
        String str38 = "Polymorphism";
        String str39 = "Encapsulation";
        String str40 = "Abstraction";
        String str41 = "Exception";
        String str42 = "Handling";
        String str43 = "Input";
        String str44 = "Output";
        String str45 = "Files";
        String str46 = "Streams";
        String str47 = "Threads";
        String str48 = "Concurrency";
        String str49 = "Synchronization";
        String str50 = "Networking";
        String str51 = "Protocols";
        String str52 = "HTTP";
        String str53 = "Sockets";
        String str54 = "Servers";
        String str55 = "Clients";
        String str56 = "Databases";
        String str57 = "SQL";
        String str58 = "Queries";
        String str59 = "Transactions";
        String str60 = "Security";
        String str61 = "Encryption";
        String str62 = "Decryption";
        String str63 = "Authentication";
        String str64 = "Authorization";
        String str65 = "Validation";
        String str66 = "Testing";
        String str67 = "Debugging";
        String str68 = "Deployment";
        String str69 = "CI";
        String str70 = "CD";
        String str71 = "DevOps";
        String str72 = "Cloud";
        String str73 = "Computing";
        String str74 = "Virtualization";
        String str75 = "Containers";

        String concat1 = str1 + str2;
        String concat2 = str3 + str4;
        String concat3 = str5 + str6;
        String concat4 = str7 + str8;
        String concat5 = str9 + str10;
        String concat6 = str11 + str12;
        String concat7 = str13 + str14;
        String concat8 = str15 + str16;
        String concat9 = str17 + str18;
        String concat10 = str19 + str20;
        String concat11 = str21 + str22;
        String concat12 = str23 + str24;
        String concat13 = str25 + str26;
        String concat14 = str27 + str28;
        String concat15 = str29 + str30;
        String concat16 = str31 + str32;
        String concat17 = str33 + str34;
        String concat18 = str35 + str36;
        String concat19 = str37 + str38;
        String concat20 = str39 + str40;
        String concat21 = str41 + str42;
        String concat22 = str43 + str44;
        String concat23 = str45 + str46;
        String concat24 = str47 + str48;
        String concat25 = str49 + str50;
        String concat26 = str51 + str52;
        String concat27 = str53 + str54;
        String concat28 = str55 + str56;
        String concat29 = str57 + str58;
        String concat30 = str59 + str60;
        String concat31 = str61 + str62;
        String concat32 = str63 + str64;
        String concat33 = str65 + str66;
        String concat34 = str67 + str68;
        String concat35 = str69 + str70;
        String concat36 = str71 + str72;
        String concat37 = str73 + str74;
        String concat38 = str75 + str1;
        String concat39 = str2 + str3;
        String concat40 = str4 + str5;
        String concat41 = str6 + str7;
        String concat42 = str8 + str9;
        String concat43 = str10 + str11;
        String concat44 = str12 + str13;
        String concat45 = str14 + str15;
        String concat46 = str16 + str17;
        String concat47 = str18 + str19;
        String concat48 = str20 + str21;
        String concat49 = str22 + str23;
        String concat50 = str24 + str25;
        String concat51 = str26 + str27;
        String concat52 = str28 + str29;
        String concat53 = str30 + str31;
        String concat54 = str32 + str33;
        String concat55 = str34 + str35;
        String concat56 = str36 + str37;
        String concat57 = str38 + str39;
        String concat58 = str40 + str41;
        String concat59 = str42 + str43;
        String concat60 = str44 + str45;
        String concat61 = str46 + str47;
        String concat62 = str48 + str49;
        String concat63 = str50 + str51;
        String concat64 = str52 + str53;
        String concat65 = str54 + str55;
        String concat66 = str56 + str57;
        String concat67 = str58 + str59;
        String concat68 = str60 + str61;
        String concat69 = str62 + str63;
        String concat70 = str64 + str65;
        String concat71 = str66 + str67;
        String concat72 = str68 + str69;
        String concat73 = str70 + str71;
        String concat74 = str72 + str73;
        String concat75 = str74 + str75;

        System.out.println(str1);
        System.out.println(str2);
        System.out.println(str3);
        System.out.println(str4);
        System.out.println(str5);
        System.out.println(str6);
        System.out.println(str7);
        System.out.println(str8);
        System.out.println(str9);
        System.out.println(str10);
        System.out.println(str11);
        System.out.println(str12);
        System.out.println(str13);
        System.out.println(str14);
        System.out.println(str15);
        System.out.println(str16);
        System.out.println(str17);
        System.out.println(str18);
        System.out.println(str19);
        System.out.println(str20);
        System.out.println(str21);
        System.out.println(str22);
        System.out.println(str23);
        System.out.println(str24);
        System.out.println(str25);
        System.out.println(str26);
        System.out.println(str27);
        System.out.println(str28);
        System.out.println(str29);
        System.out.println(str30);
        System.out.println(str31);
        System.out.println(str32);
        System.out.println(str33);
        System.out.println(str34);
        System.out.println(str35);
        System.out.println(str36);
        System.out.println(str37);
        System.out.println(str38);
        System.out.println(str39);
        System.out.println(str40);
        System.out.println(str41);
        System.out.println(str42);
        System.out.println(str43);
        System.out.println(str44);
        System.out.println(str45);
        System.out.println(str46);
        System.out.println(str47);
        System.out.println(str48);
        System.out.println(str49);
        System.out.println(str50);
        System.out.println(str51);
        System.out.println(str52);
        System.out.println(str53);
        System.out.println(str54);
        System.out.println(str55);
        System.out.println(str56);
        System.out.println(str57);
        System.out.println(str58);
        System.out.println(str59);
        System.out.println(str60);
        System.out.println(str61);
        System.out.println(str62);
        System.out.println(str63);
        System.out.println(str64);
        System.out.println(str65);
        System.out.println(str66);
        System.out.println(str67);
        System.out.println(str68);
        System.out.println(str69);
        System.out.println(str70);
        System.out.println(str71);
        System.out.println(str72);
        System.out.println(str73);
        System.out.println(str74);
        System.out.println(str75);
System.out.println("========================================================");
        System.out.println(concat1);
        System.out.println(concat2);
        System.out.println(concat3);
        System.out.println(concat4);
        System.out.println(concat5);
        System.out.println(concat6);
        System.out.println(concat7);
        System.out.println(concat8);
        System.out.println(concat9);
        System.out.println(concat10);
        System.out.println(concat11);
        System.out.println(concat12);
        System.out.println(concat13);
        System.out.println(concat14);
        System.out.println(concat15);
        System.out.println(concat16);
        System.out.println(concat17);
        System.out.println(concat18);
        System.out.println(concat19);
        System.out.println(concat20);
        System.out.println(concat21);
        System.out.println(concat22);
        System.out.println(concat23);
        System.out.println(concat24);
        System.out.println(concat25);
        System.out.println(concat26);
        System.out.println(concat27);
        System.out.println(concat28);
        System.out.println(concat29);
        System.out.println(concat30);
        System.out.println(concat31);
        System.out.println(concat32);
        System.out.println(concat33);
        System.out.println(concat34);
        System.out.println(concat35);
        System.out.println(concat36);
        System.out.println(concat37);
        System.out.println(concat38);
        System.out.println(concat39);
        System.out.println(concat40);
        System.out.println(concat41);
        System.out.println(concat42);
        System.out.println(concat43);
        System.out.println(concat44);
        System.out.println(concat45);
        System.out.println(concat46);
        System.out.println(concat47);
        System.out.println(concat48);
        System.out.println(concat49);
        System.out.println(concat50);
        System.out.println(concat51);
        System.out.println(concat52);
        System.out.println(concat53);
        System.out.println(concat54);
        System.out.println(concat55);
        System.out.println(concat56);
        System.out.println(concat57);
        System.out.println(concat58);
        System.out.println(concat59);
        System.out.println(concat60);
        System.out.println(concat61);
        System.out.println(concat62);
        System.out.println(concat63);
        System.out.println(concat64);
        System.out.println(concat65);
        System.out.println(concat66);
        System.out.println(concat67);
        System.out.println(concat68);
        System.out.println(concat69);
        System.out.println(concat70);
        System.out.println(concat71);
        System.out.println(concat72);
        System.out.println(concat73);
        System.out.println(concat74);
        System.out.println(concat75);
    }
}
